search:
  url: "/search"
  description: "Search"
show:
  url: "/show"
  description: "Viewing Item"
artworks:
  url: "/artworks"
  description: "Browse Artworks"
cart:
  url: "/yourcart"
  description: "Your Cart"
account:
  url: "/account"
  description: "Account"
openshop:
  url: "/openshop"
  description: "Open a Shop"
shop:
  url: "/yourshop"
  description: "Your Shop"
orders:
  url: "/orders"
  description: "Your Orders"
settings:
  url: "/users/edit"
  description: "User Settings"
