Photos:
  url: "/category/photography"
  description: "Photographs"
Sculptures:
  url: "/category/sculpture"
  description: "Sculptures"
Paintings:
  url: "/category/painting"
  description: "Paintings"
