Photos:
  url: "/category/photos"
  description: "Photographs"
Sculptures:
  url: "/category/sculptures"
  description: "Sculptures"
Paintings:
  url: "/category/paintings"
  description: "Paintings"
