All Artworks:
  url: "/browse/all"
  description: "All artworks"
Photos:
  url: "/browse/photography"
  description: "Photographs"
Sculptures:
  url: "/browse/sculpture"
  description: "Sculptures"
Paintings:
  url: "/browse/painting"
  description: "Paintings"
