Photos:
  url: "/artworks/photography"
  description: "Photographs"
Sculptures:
  url: "/artworks/sculpture"
  description: "Sculptures"
Paintings:
  url: "/artworks/painting"
  description: "Paintings"
